#pragma kernel CSMain

RWStructuredBuffer<int> buffer;

[numthreads(8, 8, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //Basically some random calculations
    if (id.x % 2 == 0)
    {
        buffer[id.x * 10 + id.y] = 10 + id.x * id.y;
    }
    else if (id.y % 2 == 0)
    {
        buffer[id.x * 10 + id.y] = 10 * id.x + id.y;
    }
    else
    {
        buffer[id.x * 10 + id.y] = 10 + id.x + id.y;
    }
}